name: Validate MegaGlest mod

on:
  push:
    branches:
      - master
    tags:
      - v**
  pull_request:
    branches:
      - master

jobs:
  validate-mod:
    runs-on: ubuntu-latest
    env:
      MOD_NAME: readypack-testing
      RELEASE_NAME: 'readypack'
    steps:
    - uses: actions/checkout@v3
    - if: ${{ github.ref_type == 'tag' }}
      run: |
        MOD_VERSION=${{ github.ref_name }}
        echo "MOD_VERSION=${MOD_VERSION:1}" >> $GITHUB_ENV
    - uses:  megaglest/gh-action-validate-megaglest-mod@v1
      with:
        name: ${{ env.MOD_NAME }}
        release_name: ${{ env.RELEASE_NAME }}
        type: tech
    - if: ${{ github.ref_type == 'tag' }}
      name: Make 7z and sha256sum
      run: |
        OUT_FILE="$RELEASE_NAME-$MOD_VERSION"
        cd output/$RELEASE_NAME
        sudo mv $RELEASE_NAME.xml "$OUT_FILE".xml
        cd ..
        sudo mv "$RELEASE_NAME" "$OUT_FILE"
        7z a "$OUT_FILE.7z" "$OUT_FILE"
        sudo rm -rf "$OUT_FILE"
        cd output
        sha256sum "$OUT_FILE.7z" > "$OUT_FILE.7z.sha256sum"
    - if: ${{ github.ref_type == 'tag' }}
      name: Release Mod
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        prerelease: False
        artifacts: "output/${{ env.RELEASE_NAME }}*.*"
        token: ${{ secrets.GITHUB_TOKEN }}
        omitNameDuringUpdate: True
        omitBodyDuringUpdate: True
