name: Validate MegaGlest mod

on:
  push:
    branches:
      - master
    tags:
      - v**
  pull_request:
    branches:
      - master

jobs:
  validate-mod:
    runs-on: ubuntu-latest
    env:
      MOD_NAME: readypack-testing
      RELEASE_NAME: 'readypack'
    steps:
    - uses: actions/checkout@v3
    - if: ${{ github.ref_type == 'tag' }}
      run: |
        MOD_VERSION: ${{ github.ref_name }}
        echo "MOD_VERSION=${MOD_VERSION:1}" >> $GITHUB_ENV
    - uses:  megaglest/gh-action-validate-megaglest-mod@v1
      with:
        name: ${{ env.MOD_NAME }}
        release_name: ${{ env.RELEASE_NAME }}
        type: tech
    - if: ${{ github.ref_type == 'tag' }}
      name: Make 7z
      run: |
        cd output/$RELEASE_NAME
        sudo mv $RELEASE_NAME.xml $RELEASE_NAME-$MOD_VERSION.xml
        cd ..
        sudo mv $RELEASE_NAME $RELEASE_NAME-$MOD_VERSION
        7z a $RELEASE_NAME-$MOD_VERSION.7z $RELEASE_NAME-$MOD_VERSION
        sudo rm -rf $RELEASE_NAME-$MOD_VERSION
    - if: ${{ github.ref_type == 'tag' }}
      name: Create sha256sum
      run:  |
        OUTPUT_FILE="$RELEASE_NAME-$MOD_VERSION.7z"
        cd output
        sha256sum $OUTPUT_FILE > $OUTPUT_FILE.sha256sum
    - if: ${{ github.ref_type == 'tag' }}
      name: Release Mod
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        prerelease: False
        artifacts: "output/${{ env.RELEASE_NAME }}*.*"
        token: ${{ secrets.GITHUB_TOKEN }}
        omitNameDuringUpdate: True
        omitBodyDuringUpdate: True
